### ISSUE TITLE
Pull request #1 not pushed to arduino

### ISSUE THREAD

**Issue by axelvanherle** [tripplefox/TsicSensor#2]
Like title suggest, PR #1 is not pushed to arduino libraries. The library manager gives you the outdated version that does not compile on linux. You can just fix it manually though

**Comment by tripplefox** [comment]
Ah, yes... It seems that I forgot to make new releases for the last changes, sorry. Additionally the version attribute in the library.property file was not updated...

So I corrected the version attribute and made a new release (1.0.2) of the library. It should show up in the Arduino library listing soon.

**Comment by axelvanherle** [comment]
All good, no problem was just letting you know :smile:. I got it to work by manually altering it anyways.

Nice project, by the by.

**Comment by tripplefox** [comment]
Thank you for using it 😁!

By the way: it looks like the Arduino Library Manager ignored the last bugfix release (1.0.1) because of the wrong version attribute. So i would recommend to download and use the newest version 1.0.2
